Admin frontend
bcgov/workbc-wage-subsidy pull request #54
Opened 2023-07-10 16:22 UTC by strdavis

- [x] Implement global layout and styling.
- [x] Rename wage to applications.
- [x] Always filter out drafts.
- [x] Implement catchment handling and state management.
- [x] Implement applications datagrid.
- [x] Implement applications status sidebar.
- [x] Implement catchment dropdown (with default styling).
- [x] Implement catchment label.
- [x] Implement Notify button styling (no notification functionality).

2023-08-16 23:49 UTC, brankoEISI requested changes

2023-08-16 23:49 UTC, brankoEISI commented on packages/admin-client/src/Applications/ApplicationList.tsx
> +        console.log("row click")
Should remove the console logs and put the commented out temporary click functionality back in

2023-08-16 23:49 UTC, brankoEISI commented on packages/admin-client/src/Claims/ClaimList.tsx
> +        console.log("row click")
remove console logs

2023-08-16 23:49 UTC, brankoEISI commented on packages/admin-client/src/common/components/CalculatorButtonField/CalculatorButtonField.tsx
> +                console.log("calculator button")
remove console logs

2023-08-16 23:49 UTC, brankoEISI commented on packages/admin-client/src/common/components/PdfButtonField/PdfButtonField.tsx
> +                console.log("pdf button")
console logs

2023-08-16 23:49 UTC, brankoEISI commented on packages/admin-client/src/common/contexts/CatchmentContext/CatchmentContext.tsx
> +        for (let i = 1; i <= 45; i += 1) {
put the 45 into a constant at the top of the file, something like 
```javascript
const NUM_CATCHMENTS = 45
```

2023-08-16 23:49 UTC, brankoEISI commented on packages/admin-client/src/common/contexts/CatchmentContext/CatchmentContext.tsx
> +    let result: any[] | undefined = []
result will never be undefined if you're instantiating it as an empty array and only doing pushes on it

2023-08-16 23:49 UTC, brankoEISI commented on packages/admin-client/src/common/contexts/CatchmentContext/CatchmentContext.tsx
> +            result?.push({
don't need the ? null check, same reason as above

2023-08-16 23:49 UTC, brankoEISI commented on packages/admin-client/src/common/contexts/CatchmentContext/CatchmentContext.tsx
> +            result?.push({ id: i, name: `${i}` })
don't need null check

2023-08-25 00:19 UTC, strdavis commented on packages/admin-api/src/services/claims.service.ts
> +        numUpdated = await knex("claims")
It does appear to return the number of records updated.

2023-08-29 19:47 UTC, brankoEISI approved these changes

2023-08-29 19:51 UTC, merged